// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Este arquivo só alimenta o CLI (migrate/db pull), que precisa da
    // conexão DIRETA do Supabase (5432) — o pooler de transação não suporta
    // DDL direito. O app em runtime usa o pooler via adapter em lib/prisma.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
